### ISSUE TITLE
not starting 

### ISSUE THREAD

**Issue by 69frelon** [bandademan/ITBMorePlayers#1]
Inside the Backrooms MorePlayers v1.0.0' is incompatible:

this is the melon loader log 

[MelonLoader_22-12-22_20-19-23.626.log](https://github.com/bandademan/ITBMorePlayers/files/10289155/MelonLoader_22-12-22_20-19-23.626.log)

**Comment by bandademan** [comment]
What version of the game are you running?

**Comment by 69frelon** [comment]
latest

**Comment by bandademan** [comment]
Oh i was confused for a second cause Melonloader 0.5.7 doesnt work with the newest version 0.2.1 of the game

**Comment by bandademan** [comment]
I know what your issue is give me one second and ill push an update

**Comment by bandademan** [comment]
No problem, are you sure your on version 0.2.0 of ITB cause your log states your playing on a different version?

**Comment by bandademan** [comment]
Whats the version number say at the bottom left when your in the main menu?

**Comment by 69frelon** [comment]
0.2.1d

**Comment by bandademan** [comment]
Interesting cause MelonLoader v0.5.7 doesnt work with the 0.2.1 versions of ITB, however this shouldn't cause any issues with the push I just made, so you can download the new dll and use that. Let me know if theres any issues.

**Comment by 69frelon** [comment]
okay thanks

**Comment by bandademan** [comment]
No problem, Ill close this issue and if you have any other feel free to open another issue.

**Comment by 69frelon** [comment]
Assertion: should not be reached at ..\mono\mini\tramp-amd64.c:229

**Comment by 69frelon** [comment]
idk what that means i saw the log its all good but the melon loader thing says that

**Comment by 69frelon** [comment]
should i try using a different version  of melonloader

**Comment by bandademan** [comment]
Yeah thats what i was expecting from using 5.7 on the newest version, you have to use a nightly build of melonloader, heres a link to there nightly builds https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development

**Comment by bandademan** [comment]
The melonloader devs are working on a fix cause its something to do with newer unity versions so for right now youd have to use this nightly and a lot of mods will be broken with the nightly builds, however the Moreplayers mod will work fine.

**Comment by bandademan** [comment]
You can use MelonLoader 0.5.7 on ITB 0.2.0 versions and lower its just 0.2.1 that youll need the nightly build of ML

**Comment by 69frelon** [comment]
yeah it worked thanks man
